In [1]:
import numpy as np

In [2]:
x = np.array([2,4,6,7,3,1,2,45,67,32,54,7])

In [3]:
print(x)

[ 2  4  6  7  3  1  2 45 67 32 54  7]


In [4]:
x[0]

2

In [5]:
x[0:4]

array([2, 4, 6, 7])

# List Vs Numpy Array

In [6]:
np_x = np.array([])
list_x = []

# Memory Comparison

In [7]:
import sys

In [8]:
sys.getsizeof(np_x)

96

In [9]:
sys.getsizeof(list_x)

64

In [12]:
size = range(10000)
list_x = list(size)
sys.getsizeof(list_x)

90112

In [13]:
size = range(10000)
np_x = np.array(size)
sys.getsizeof(np_x)

40096

In [25]:
list_x1 = [i for i in range(10000000)]
list_x2 = list_x1[:]

In [26]:
import time

In [27]:
start = time.time()
list_3 = []
for i in range(len(list_x1)):
    list_3.append(list_x1[i] + list_x2[i])
end = time.time()
total = end - start
print("Total time taken is",total)

Total time taken is 5.026262521743774


In [29]:
x1 = np.array([i for i in range(10000000)])
x2 = np.array([i for i in range(10000000)])

In [30]:
start = time.time()
x3 = x1 + x2
end = time.time()
total = end - start
print("Total time taken is",total)

Total time taken is 0.03504681587219238


In [34]:
np.array([1,2,3,5,5,True,10.5])

array([ 1. ,  2. ,  3. ,  5. ,  5. ,  1. , 10.5])