In [1]:
import numpy as np

In [7]:
np.random.seed(5)

In [8]:
age = np.random.randint(10,100,20)

In [9]:
age

array([88, 71, 26, 83, 18, 72, 37, 40, 90, 17, 86, 25, 63, 90, 37, 54, 87,
       85, 75, 57])

In [10]:
sum(age) / len(age)

60.05

In [11]:
np.mean(age)

60.05

In [12]:
np.median(age)

67.0

In [13]:
len(age)

20

In [14]:
np.sort(age)

array([17, 18, 25, 26, 37, 37, 40, 54, 57, 63, 71, 72, 75, 83, 85, 86, 87,
       88, 90, 90])

In [16]:
(63 + 71) / 2

67.0

In [18]:
np.max(age)

90

In [19]:
np.argmax(age)

8

In [20]:
np.min(age)

17

In [21]:
np.argmin(age)

9

In [22]:
np.argsort(age)

array([ 9,  4, 11,  2, 14,  6,  7, 15, 19, 12,  1,  5, 18,  3, 17, 10, 16,
        0, 13,  8], dtype=int64)

In [24]:
# sorted(age, reverse=True)

In [28]:
x = np.random.randint(10,20,(4,4,4))

In [29]:
x

array([[[19, 13, 12, 14],
        [16, 19, 13, 13],
        [12, 11, 15, 17],
        [14, 13, 11, 17]],

       [[13, 11, 19, 15],
        [17, 10, 19, 16],
        [10, 15, 12, 18],
        [16, 18, 10, 15]],

       [[12, 10, 17, 17],
        [16, 10, 10, 18],
        [15, 15, 19, 16],
        [14, 15, 12, 18]],

       [[18, 11, 16, 13],
        [14, 11, 18, 10],
        [12, 12, 14, 11],
        [16, 13, 14, 13]]])

In [30]:
x.flatten()

array([19, 13, 12, 14, 16, 19, 13, 13, 12, 11, 15, 17, 14, 13, 11, 17, 13,
       11, 19, 15, 17, 10, 19, 16, 10, 15, 12, 18, 16, 18, 10, 15, 12, 10,
       17, 17, 16, 10, 10, 18, 15, 15, 19, 16, 14, 15, 12, 18, 18, 11, 16,
       13, 14, 11, 18, 10, 12, 12, 14, 11, 16, 13, 14, 13])

In [33]:
np.hstack(x)

array([[19, 13, 12, 14, 13, 11, 19, 15, 12, 10, 17, 17, 18, 11, 16, 13],
       [16, 19, 13, 13, 17, 10, 19, 16, 16, 10, 10, 18, 14, 11, 18, 10],
       [12, 11, 15, 17, 10, 15, 12, 18, 15, 15, 19, 16, 12, 12, 14, 11],
       [14, 13, 11, 17, 16, 18, 10, 15, 14, 15, 12, 18, 16, 13, 14, 13]])

In [35]:
x1 = np.vstack(x)

In [36]:
x1.shape

(16, 4)

In [37]:
x.shape

(4, 4, 4)