In [1]:
import numpy as np

In [2]:
x1 = np.array([3,5,6,7,32,4,7,7,32,56,7,78])

In [3]:
# similar to python range function
x2 = np.arange(6)

In [4]:
x2

array([0, 1, 2, 3, 4, 5])

In [5]:
# it has start, stop, step
x2 = np.arange(1,21,2)

In [6]:
x2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
# Linear Space
# it will return a linear array of 50 numbers (by default) within a range
# here it will return a linear array of 20 numbers b/w 10 to 20
x3 = np.linspace(10,20,retstep=True,num=20)

In [12]:
x3

(array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
        12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
        15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
        17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ]),
 0.5263157894736842)

In [17]:
x4 = np.ndarray((2,2,2,2))

In [18]:
x4

array([[[[4.67296746e-307, 1.69121096e-306],
         [1.86921822e-306, 1.11256817e-306]],

        [[1.06811422e-306, 1.42417221e-306],
         [1.11260619e-306, 8.90094053e-307]]],


       [[[1.86919378e-306, 1.06809792e-306],
         [1.37962456e-306, 1.69111861e-306]],

        [[1.78020169e-306, 1.37961777e-306],
         [7.56599807e-307, 2.56761491e-312]]]])

In [19]:
x4.shape

(2, 2, 2, 2)

In [20]:
x4.ndim

4

In [21]:
x5 = np.random.random(size=(5,5))

In [22]:
x5

array([[0.01042821, 0.15309005, 0.18039466, 0.54900449, 0.88315918],
       [0.95035119, 0.71138134, 0.86738492, 0.59709002, 0.588925  ],
       [0.14232449, 0.71237709, 0.58098976, 0.35257652, 0.39809757],
       [0.29339847, 0.56248682, 0.32422079, 0.63644477, 0.83625864],
       [0.79387873, 0.4661157 , 0.64013851, 0.48126746, 0.96447717]])

In [39]:
x6 = np.random.randint(10,100,(2,2))

In [40]:
x6

array([[62, 73],
       [83, 94]])

In [37]:
 x7 = np.random.random_integers(10,20,(4,4))  

C:\Users\asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(10, 20 + 1) instead
  """Entry point for launching an IPython kernel.


In [38]:
x7

array([[11, 20, 18, 13],
       [10, 11, 15, 12],
       [15, 16, 19, 19],
       [19, 14, 11, 13]])

In [41]:
x7[0]

array([11, 20, 18, 13])

In [42]:
x7[0][0]

11

In [44]:
x7[0:2]

array([[11, 20, 18, 13],
       [10, 11, 15, 12]])

In [46]:
x7[0:2,2:]

array([[18, 13],
       [15, 12]])

In [49]:
x8 = np.zeros((5,5))

In [50]:
x8

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
x9 = np.ones((5,3))

In [54]:
x9

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
x10 = np.identity(4)

In [57]:
x10

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])